<a href="https://colab.research.google.com/github/Junaeid-Shoaib/AI_Agents/blob/main/PyTorch_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.9.0+cu126


In [ ]:
if torch.cuda.is_available():
    print(f"{torch.cuda.get_device_name(0)} GPU is available")
else:
    print("GPU is not available")

Tesla T4 GPU is available


# Creating Tensor

In [ ]:
#using empty
x = torch.empty(2,3)
print(x)

tensor([[-5.7981e+26,  4.4233e-41,  1.7832e-21],
        [ 0.0000e+00,  1.9191e-21,  0.0000e+00]])


In [ ]:
#check type
type(x)


torch.Tensor

In [ ]:
#using zero
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#using one
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#using rand
x = torch.rand(2,3)
print(x)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [ ]:
#using manual seed for reproducibilty
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
#using tensor
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
#using arange
x = torch.arange(0,32,2).reshape(4,4)
print(x)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30]])


In [ ]:
#using linspace
x = torch.linspace(0,32,16).reshape(4,4)
print(x)

tensor([[ 0.0000,  2.1333,  4.2667,  6.4000],
        [ 8.5333, 10.6667, 12.8000, 14.9333],
        [17.0667, 19.2000, 21.3333, 23.4667],
        [25.6000, 27.7333, 29.8667, 32.0000]])


In [ ]:
#using full
x = torch.full((2,3),4)
print(x)

tensor([[4, 4, 4],
        [4, 4, 4]])


In [ ]:
#using eye
x = torch.eye(3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Copying the shape

In [ ]:
# using like
torch.zeros_like(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using like
torch.full_like(x,5)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [ ]:
x.dtype

torch.float32

In [ ]:
torch.randint_like(x, low=0, high=10, dtype=torch.int64)

tensor([[0, 4, 0],
        [3, 8, 4],
        [0, 4, 1]])

Math operation

In [ ]:
torch.manual_seed(42)
x = torch.randint(size=(2,3), low=0, high=10)


In [ ]:
x

tensor([[2, 7, 6],
        [4, 6, 5]])

In [ ]:
torch.sum(x)

tensor(30)

In [ ]:
torch.sum(x, dim=0) #column wise

tensor([ 6, 13, 11])

In [ ]:
torch.sum(x, dim=1) #row wise

tensor([15, 15])

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
torch.manual_seed(42)
x = torch.rand(2,3).to(device)
x

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0')

In [ ]:
x + 5

tensor([[5.8823, 5.9150, 5.3829],
        [5.9593, 5.3904, 5.6009]], device='cuda:0')

In [ ]:
import time
import torch

size = 10000
m1 = torch.rand(size,size)
m2 = torch.rand(size,size)

start = time.time()
mr = torch.matmul(m1,m2)
end = time.time()
cpu = end-start
print(f'CPU: {cpu}')

m1_gpu = m1.to('cuda')
m2_gpu = m2.to('cuda')
start1 = time.time()
mr_gpu = torch.matmul(m1_gpu,m2_gpu)
end1 = time.time()
gpu = end1-start1
print(f'GPU: {gpu}')

print(cpu/gpu)



CPU: 16.541486978530884
GPU: 0.13882946968078613
119.14968065904965


In [ ]:
torch.manual_seed(42)
x = torch.rand(2,3)
x

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
import numpy as np
y = x.numpy()
print(y)

[[0.88226926 0.91500396 0.38286376]
 [0.95930564 0.3904482  0.60089535]]


In [ ]:
torch.from_numpy(y)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])